Bruh Momento
t0xic0der/fedora-easyfix pull request #33
Opened 2021-10-02 13:35 UTC by khallnayak

Created Dockerfile with flexibility for changing port and ip version. #24 

# BUILD

```
docker build -t fedora-easyfix:1.0 .
```

# RUN
## Default port option
```
docker run -it -p 9696:9696 fedora-easyfix:1.0
```

## Different port number

```
docker run -it -p <Port number>:<Port number> fedora-easyfix:1.0 -4 -p <Port number>
```

### GG

2021-10-02 13:36 UTC, khallnayak commented
Please Hacktoberfest accept kar

2021-10-03 06:26 UTC, t0xic0der requested changes
Please make the requested changes.

2021-10-03 06:26 UTC, t0xic0der commented on Dockerfile
> +LABEL maintainer "khallnayak <mahijmomin@gmail.com>"
```suggestion
LABEL maintainer "Mahij Momin <mahijmomin@gmail.com>"
```

2021-10-03 06:26 UTC, t0xic0der commented on Dockerfile
> +    python3 setup.py install
```suggestion
RUN apk add git
RUN pip3 install -r requirements.txt
RUN python3 setup.py install
```

2021-10-03 06:29 UTC, t0xic0der approved these changes
LGTM.

2021-10-03 06:30 UTC, merged