Dockerfile documentation
t0xic0der/fedora-easyfix pull request #35
Opened 2021-10-04 13:43 UTC by khallnayak

Created documentation for #33 against #34

2021-10-05 01:25 UTC, t0xic0der requested changes
As the command-line flags are mostly the same for Podman and Docker, I would suggest you to have just one set of instructions which are applicable to both. Take for instance, explain the steps with Podman as a default and add a note that these would work just fine with Docker.

2021-10-05 01:25 UTC, t0xic0der commented on README.md
> +3. Build the image `docker build -t fedora-easyfix:1.0 .`.
```suggestion
3. Build the image `docker build . -f Dockerfile -t fedora-easyfix:latest`.
```

2021-10-05 01:25 UTC, t0xic0der commented on README.md
> +3. Build the image `podman build -t fedora-easyfix:1.0 -f Dockerfile`.
```suggestion
3. Build the image `podman build . -f Dockerfile -t fedora-easyfix:latest`.
```

2021-10-05 01:25 UTC, t0xic0der commented on README.md
> +   - Run with default port options`podman run -it -d -p 9696:9696 fedora-easyfix:1.0`.
```suggestion
   - Run with default port options `podman run -it -p 9696:9696 fedora-easyfix:latest -4`.
```

2021-10-05 01:25 UTC, t0xic0der commented on README.md
> +   - Run with custom port options`podman run -it -d -p <Port number>:<Port number> fedora-easyfix:1.0 -4 -p <Port number>`.
```suggestion
   - Run with custom port options `podman run -it -p <port number>:<port number> fedora-easyfix:latest -4 -p <port number>`.
```

2021-10-09 05:30 UTC, khallnayak commented
The changes have been made as per requested.

2021-10-09 06:45 UTC, closed without merging